module.exports = {
  plugins: [
    'eslint-plugin-jsonc',
  ],
  rules: {
    'jsonc/comma-dangle': ['error', { arrays: 'never', objects: 'never' }],
    'jsonc/comma-style': ['error', 'last'],

    'jsonc/array-bracket-newline': ['error', 'consistent'],
    'jsonc/array-bracket-spacing': 'error',
    'jsonc/array-element-newline': ['error', 'consistent'],

    'jsonc/key-name-casing': 'off',
    'jsonc/key-spacing': ['error', { afterColon: true, beforeColon: false, mode: 'strict' }],
    'jsonc/no-bigint-literals': 'error',
    'jsonc/no-binary-expression': 'error',
    'jsonc/no-binary-numeric-literals': 'error',
    'jsonc/no-comments': 'off',
    'jsonc/no-dupe-keys': 'error',
    'jsonc/no-escape-sequence-in-identifier': 'error',
    'jsonc/no-floating-decimal': 'error',
    'jsonc/no-hexadecimal-numeric-literals': 'error',
    'jsonc/no-infinity': 'error',
    'jsonc/no-multi-str': 'error',
    'jsonc/no-nan': 'error',
    'jsonc/no-number-props': 'error',
    'jsonc/no-numeric-separators': 'error',
    'jsonc/no-octal': 'error',
    'jsonc/no-octal-escape': 'error',
    'jsonc/no-octal-numeric-literals': 'error',
    'jsonc/no-parenthesized': 'error',
    'jsonc/no-plus-sign': 'error',
    'jsonc/no-regexp-literals': 'error',
    'jsonc/no-sparse-arrays': 'error',
    'jsonc/no-template-literals': 'error',
    'jsonc/no-undefined-value': 'error',
    'jsonc/no-unicode-codepoint-escapes': 'error',
    'jsonc/no-useless-escape': 'error',
    'jsonc/object-curly-newline': ['error', { consistent: true, minProperties: 4 }],
    'jsonc/object-curly-spacing': ['error', 'always'],
    'jsonc/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'jsonc/quote-props': ['error', 'always'],
    'jsonc/quotes': ['error', 'double', { avoidEscape: false }],
    'jsonc/sort-array-values': 'off',
    'jsonc/sort-keys': 'off',
    'jsonc/space-unary-ops': 'error',
    'jsonc/valid-json-number': 'error',
    'jsonc/vue-custom-block/no-parsing-error': 'error',
  },
  overrides: [
    {
      files: ['*.json', '*.json5', '.eslintrc'],
      parser: 'jsonc-eslint-parser',
      rules: {
        // 强制缩进（默认 2 个空格）
        'jsonc/indent': ['error', 2],
        'no-multiple-empty-lines': ['error', { max: 0, maxEOF: 1 }],
      },
    },
  ],
}
